apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-rq
  namespace: oiga-users-svc
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://localhost:15672"
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
scopes:
  - oiga-user-service
  - oiga-search-service